# Generated by Django 5.2 on 2025-04-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_team_description_room_rool_team_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.room'),
        ),
    ]
